/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import KOM.Komunikacija;
import domen.Korisnik;
import domen.Poruka;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import niti.Prijem;

/**
 *
 * @author Korisnik
 */
public class KlijentskaForma extends javax.swing.JFrame {

    Korisnik ulogovani;
    ArrayList<Korisnik> onlineKorisnici = new ArrayList<>();
    ArrayList<Poruka> poruke = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    SimpleDateFormat vr = new SimpleDateFormat("HH:mm");
    
    
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma(Korisnik k) {
        initComponents();
        ulogovani = k;
        pripremiTabelu();
        Komunikacija.getInstance().setKf(this);
        Komunikacija.getInstance().pokreniPrijem();
        Komunikacija.getInstance().vratiOnlineKorisnike();
        labela.setText(k.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPoruka = new javax.swing.JTextField();
        btnSvima = new javax.swing.JButton();
        btnSamo = new javax.swing.JButton();
        cb = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        labela = new javax.swing.JLabel();
        btnprikazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSvima.setText("Posalji svima");
        btnSvima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSvimaActionPerformed(evt);
            }
        });

        btnSamo.setText("Posalji samo");
        btnSamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSamoActionPerformed(evt);
            }
        });

        jButton3.setText("LOG OUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabela);

        labela.setText("Korisnik");

        btnprikazi.setText("Prikazi poruku");
        btnprikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprikaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPoruka)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSvima)
                        .addGap(28, 28, 28)
                        .addComponent(btnSamo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labela)
                        .addGap(185, 185, 185)
                        .addComponent(btnprikazi)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSvima)
                    .addComponent(btnSamo)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(labela)
                    .addComponent(btnprikazi)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Komunikacija.getInstance().logout(ulogovani);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSamoActionPerformed
        if (onlineKorisnici.isEmpty()) return;
        if (txtPoruka.getText().isEmpty()) return;
        Korisnik KOME = onlineKorisnici.get(cb.getSelectedIndex());
        Poruka por = new Poruka(ulogovani, KOME, txtPoruka.getText(), new Date());
        Komunikacija.getInstance().posaljiPoruku(por);
        
        txtPoruka.setText("");
    }//GEN-LAST:event_btnSamoActionPerformed

    private void btnSvimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSvimaActionPerformed
        if (txtPoruka.getText().isEmpty()) return;
        
        Poruka por = new Poruka(ulogovani, txtPoruka.getText(), new Date());
        Komunikacija.getInstance().posaljiPoruku(por);        
        txtPoruka.setText("");
    }//GEN-LAST:event_btnSvimaActionPerformed

    private void btnprikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprikaziActionPerformed
        int izbor = tabela.getSelectedRow();
        if (izbor==-1) return;
        Poruka poruka = poruke.get(izbor);
        if (poruka.getTekst().length()<20) JOptionPane.showMessageDialog(rootPane, "Mora poruka imati bar 20 karaktera");
        else {
            new PrikazPoruke(this, true, poruka).setVisible(true);
        }
        
    }//GEN-LAST:event_btnprikaziActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSamo;
    private javax.swing.JButton btnSvima;
    private javax.swing.JButton btnprikazi;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labela;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtPoruka;
    // End of variables declaration//GEN-END:variables

    public void updateOnlineKorisnike(ArrayList<Korisnik> online) {
        cb.removeAllItems();
        online.remove(ulogovani);
        onlineKorisnici = online;
        for (Korisnik k: onlineKorisnici){
            cb.addItem(k.getUser());
        }
    }

    public void stiglaPoruka(Poruka poruka) {
        poruke.add(poruka);
        popuniTabelu();
    }

    private void popuniTabelu() {
        model.setRowCount(0);
        for (Poruka p: poruke){
            dodajUTabelu(p);
        }
    }

    private void pripremiTabelu() {
        model.addColumn("Vreme");
        model.addColumn("Od");
        
        model.addColumn("Tekst");
        model.addColumn("Kome");
        
        tabela.setModel(model);
    }

    private void dodajUTabelu(Poruka p) {
        Object[] o = {vr.format(p.getDatum()), p.getOD().getUser(), p.getTekst(), p.getDO() == null ? "ALL" : "meni"};
        model.addRow(o);
    }
}
